apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bdba.fullname" . }}-beat
  labels:
{{ include "bdba.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bdba.name" . }}-beat
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      name: {{ include "bdba.name" . }}-beat
      labels:
        app.kubernetes.io/name: {{ include "bdba.name" . }}-beat
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name | quote }}
        {{ with .Values.beat.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- include "bdba.configchecksum" . | nindent 8 }}
        {{ with .Values.beat.podAnnotations}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- if .Values.beat.initContainers }}
      initContainers:
      {{- range $name, $spec := .Values.beat.initContainers }}
        - name: {{ $name }}
          {{ toYaml $spec | nindent 10 }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-beat
          image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: {{ .Values.frontend.pullPolicy }}
          args: [ "beat" ]
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/celerybeat.pid
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          livenessProbe:
            exec:
              command:
              - cat
              - /tmp/celerybeat.pid
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          {{- include "bdba.frontendenv" . | nindent 10 }}
          {{- with .Values.frontend.extraEnv }}
          {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- include "bdba.frontendmounts" . | indent 12 }}
          securityContext:
            readOnlyRootFilesystem: true
          resources:
            {{- toYaml .Values.beat.resources | nindent 12 }}
        {{- if .Values.beat.sidecarContainers }}
        {{- range $name, $spec := .Values.beat.sidecarContainers }}
        - name: {{ $name }}
          {{ toYaml $spec | nindent 10 }}
        {{- end }}
        {{- end }}

      {{- if .Values.frontend.securityContext.enabled }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      {{- end }}
      volumes:
      {{- include "bdba.frontendvolumes" . | indent 8 }}

    {{- if .Values.beat.nodeSelector }}
    {{- with .Values.beat.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- else }}
    {{ with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- end }}

    {{- if .Values.beat.affinity }}
    {{- with .Values.beat.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- else }}
    {{ with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- end }}

    {{- if .Values.beat.tolerations }}
    {{- with .Values.beat.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- else }}
    {{ with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- end }}
