{{- if .Values.frontend.applicationLogging.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bdba.fullname" . }}-webapp-fluentbit-config
  labels:
{{ include "bdba.labels" . | indent 4 }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Daemon       Off
        Flush        5
        Log_Level    info
        HTTP_Server  Off
        Parsers_File /bdba-fluentbit/parsers.conf

    [INPUT]
        Name         tail
        Tag          webapp
        Path         /app-log/app.log
        Parser       json
        DB           /app-log/app.db

    [FILTER]
        Name record_modifier
        Match *
        Record hostname ${HOSTNAME}

    [OUTPUT]
        Name         forward
        Match        *
        Host         {{ template "bdba.fluentd.fullname" . }}

  parsers.conf: |
    [PARSER]
        Name        json
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L

---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bdba.fullname" . }}-webapp
  labels:
{{ include "bdba.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.frontend.web.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bdba.name" . }}-webapp
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      name: {{ include "bdba.name" . }}-webapp
      labels:
        app.kubernetes.io/name: {{ include "bdba.name" . }}-webapp
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name | quote }}
        {{ with .Values.frontend.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- include "bdba.configchecksum" . | nindent 8 }}
        {{ with .Values.frontend.podAnnotations}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- if .Values.frontend.initContainers }}
      initContainers:
      {{- range $name, $spec := .Values.frontend.initContainers }}
        - name: {{ $name }}
          {{ toYaml $spec | nindent 10 }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-webapp
          image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: {{ .Values.frontend.pullPolicy }}
          args: [ "web" ]
          readinessProbe:
            httpGet:
              port: 8000
              path: /healthz
            timeoutSeconds: 3
            initialDelaySeconds: 2
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              port: 8000
              path: /healthz/liveness
            timeoutSeconds: 3
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          {{- include "bdba.frontendenv" . | nindent 10 }}
          {{- with .Values.frontend.extraEnv }}
          {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.frontend.metrics.enabled }}
            - name: METRICS
              value: "true"
          {{- end }}
          volumeMounts:
          {{- include "bdba.frontendmounts" . | indent 12 }}
            - name: {{ include "bdba.fullname" . }}-webapp-applog
              mountPath: /app-log
          securityContext:
            readOnlyRootFilesystem: true
        {{- if .Values.frontend.applicationLogging.enabled }}
        - name: {{ .Chart.Name }}-webapp-fluentbit
          image: "{{ .Values.fluentbit.repository }}:{{ .Values.fluentbit.tag }}"
          imagePullPolicy: {{ .Values.fluentbit.pullPolicy }}
          command: ["/fluent-bit/bin/fluent-bit", "-c", "/bdba-fluentbit/fluent-bit.conf"]
          volumeMounts:
            - name:  {{ include "bdba.fullname" . }}-webapp-applog
              mountPath: /app-log
            - name: {{ include "bdba.fullname" . }}-webapp-fluentbit-config
              mountPath: /bdba-fluentbit/
        {{- end }}
        {{- if .Values.frontend.sidecarContainers }}
        {{- range $name, $spec := .Values.frontend.sidecarContainers }}
        - name: {{ $name }}
          {{ toYaml $spec | nindent 10 }}
        {{- end }}
        {{- end }}
      {{- if .Values.frontend.securityContext.enabled }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      {{- end }}
      volumes:
      {{- include "bdba.frontendvolumes" . | indent 6 }}
      - name: {{ include "bdba.fullname" . }}-webapp-applog
        emptyDir: {}
      - name: {{ include "bdba.fullname" . }}-webapp-home
        emptyDir: {}
      {{- if .Values.frontend.applicationLogging.enabled }}
      - name: {{ include "bdba.fullname" . }}-webapp-fluentbit-config
        configMap:
          name: {{ include "bdba.fullname" . }}-webapp-fluentbit-config
      {{- end }}

      {{- if .Values.frontend.nodeSelector }}
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}

      {{- if .Values.frontend.tolerations }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}

      {{- if .Values.frontend.affinity }}
      {{- with .Values.frontend.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: {{ include "bdba.name" . }}-webapp
              topologyKey: "kubernetes.io/hostname"
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bdba.fullname" . }}-webapp
  labels:
{{ include "bdba.labels" . | indent 4 }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: gunicorn
  selector:
    app.kubernetes.io/name: {{ include "bdba.name" . }}-webapp
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.frontend.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "bdba.fullname" . }}-webapp
  labels:
{{ include "bdba.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bdba.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
  - port: gunicorn
    relabelings:
      - action: labeldrop
        regex: pod
      - action: labeldrop
        regex: instance

{{- end }}
