{{- if .Values.frontend.applicationLogging.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bdba.fullname" . }}-tasks-long-fluentbit-config
  labels:
{{ include "bdba.labels" . | indent 4 }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Daemon       Off
        Flush        5
        Log_Level    info
        HTTP_Server  Off
        Parsers_File /bdba-fluentbit/parsers.conf

    [INPUT]
        Name         tail
        Tag          longjobs
        Path         /app-log/app.log
        Parser       json
        DB           /app-log/app.db

    [OUTPUT]
        Name         forward
        Match        *
        Host         {{ template "bdba.fluentd.fullname" . }}

  parsers.conf: |
    [PARSER]
        Name        json
        Format      json
        Time_Key    timestamp
        Time_Format %Y-%m-%dT%H:%M:%S.%L

---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bdba.fullname" . }}-tasks-long
  labels:
{{ include "bdba.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bdba.name" . }}-tasks-long
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      name: {{ include "bdba.name" . }}-tasks-long
      labels:
        app.kubernetes.io/name: {{ include "bdba.name" . }}-tasks-long
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name | quote }}
        {{ with .Values.taskslong.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- include "bdba.configchecksum" . | nindent 8 }}
        {{ with .Values.taskslong.podAnnotations}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
        - name: {{ .Chart.Name }}-tasks-long-wait
          image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: {{ .Values.frontend.pullPolicy }}
          args: [ "wait"]
          {{- include "bdba.frontendenv" . | nindent 10 }}
          volumeMounts:
          {{- include "bdba.frontendmounts" . | indent 12 }}
            - name: {{ include "bdba.fullname" . }}-tasks-long-applog
              mountPath: /app-log
      {{- if .Values.taskslong.initContainers }}
      {{- range $name, $spec := .Values.taskslong.initContainers }}
        - name: {{ $name }}
          {{ toYaml $spec | nindent 10 }}
      {{- end }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}-tasks-long
          image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: {{ .Values.frontend.pullPolicy }}
          args: [ "long" ]
          readinessProbe:
            exec:
              command: [ "/scripts/probe-heartbeat" ]
            initialDelaySeconds: 15
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 35
          livenessProbe:
            exec:
              command: [ "/scripts/probe-heartbeat" ]
            initialDelaySeconds: 15
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 35
          {{- include "bdba.frontendenv" . | nindent 10 }}
          {{- with .Values.frontend.extraEnv }}
          {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- include "bdba.frontendmounts" . | indent 12 }}
            - name: {{ include "bdba.fullname" . }}-tasks-long-applog
              mountPath: /app-log
          securityContext:
            readOnlyRootFilesystem: true
          resources:
            {{- toYaml .Values.taskslong.resources | nindent 12 }}
        {{- if .Values.frontend.applicationLogging.enabled }}
        - name: {{ .Chart.Name }}-tasks-long-fluentbit
          image: "{{ .Values.fluentbit.repository }}:{{ .Values.fluentbit.tag }}"
          imagePullPolicy: {{ .Values.fluentbit.pullPolicy }}
          command: ["/fluent-bit/bin/fluent-bit", "-c", "/bdba-fluentbit/fluent-bit.conf"]
          volumeMounts:
            - name:  {{ include "bdba.fullname" . }}-tasks-long-applog
              mountPath: /app-log
            - name: {{ include "bdba.fullname" . }}-tasks-long-fluentbit-config
              mountPath: /bdba-fluentbit/
          {{- end }}
        {{- if .Values.taskslong.sidecarContainers }}
        {{- range $name, $spec := .Values.taskslong.sidecarContainers }}
        - name: {{ $name }}
          {{ toYaml $spec | nindent 10 }}
        {{- end }}
        {{- end }}

      {{- if .Values.frontend.securityContext.enabled }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
      {{- end }}
      volumes:
      {{- include "bdba.frontendvolumes" . | indent 6 }}
      - name: {{ include "bdba.fullname" . }}-tasks-long-applog
        emptyDir: {}
      {{- if .Values.frontend.applicationLogging.enabled }}
      - name: {{ include "bdba.fullname" . }}-tasks-long-fluentbit-config
        configMap:
          name: {{ include "bdba.fullname" . }}-tasks-long-fluentbit-config
      {{- end }}

      {{- if .Values.taskslong.nodeSelector }}
      {{- with .Values.taskslong.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}

      {{- if.Values.taskslong.affinity}}
      {{- with .Values.taskslong.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}

      {{- if .Values.taskslong.tolerations }}
      {{- with .Values.taskslong.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
