{{- if .Values.memcached.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bdba.memcached.fullname" . }}
  labels:
{{ include "bdba.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 11211
      targetPort: 11211
      protocol: TCP
      name: memcache
  selector:
    app.kubernetes.io/name: "memcached"
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bdba.memcached.fullname" . }}
  labels:
{{ include "bdba.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "memcached"
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      name: {{ template "bdba.memcached.fullname" . }}
      labels:
        app.kubernetes.io/name: "memcached"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        release: {{ .Release.Name | quote }}
        app: "memcached"
        {{ with .Values.memcached.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{ with .Values.memcached.podAnnotations}}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- if .Values.memcached.initContainers }}
      initContainers:
      {{- range $name, $spec := .Values.memcached.initContainers }}
        - name: {{ $name }}
          {{ toYaml $spec | nindent 10 }}
      {{- end }}
      {{- end }}

      containers:
        - name: "memcached"
          image: "{{ .Values.memcached.image.repository }}:{{ .Values.memcached.image.tag }}"
          imagePullPolicy: {{ .Values.memcached.image.pullPolicy }}
          args: [ "-l", "0.0.0.0" ]
          livenessProbe:
            tcpSocket:
              port: 11211
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 11211
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          ports:
            - name: "memcache"
              containerPort: 11211
          resources:
            {{- toYaml .Values.memcached.resources | nindent 12 }}
        {{- if .Values.memcached.sidecarContainers }}
        {{- range $name, $spec := .Values.memcached.sidecarContainers }}
        - name: {{ $name }}
          {{ toYaml $spec | nindent 10 }}
        {{- end }}
        {{- end }}
      {{- if .Values.memcached.securityContext.enabled }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      {{- end }}
      {{- with .Values.memcached.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.memcached.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.memcached.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}
