{{- if or
  (and .Values.frontend.email.smtpPassword (not .Values.frontend.email.existingSecret))
  (and .Values.frontend.ldap.bindPassword (not .Values.frontend.ldap.existingSecret))
  (and .Values.frontend.licensing.username .Values.frontend.licensing.password (not .Values.frontend.licensing.existingSecret))
  (and .Values.frontend.licensing.bdportal.tenantId .Values.frontend.licensing.bdportal.clientId .Values.frontend.licensing.bdportal.clientSecret (not .Values.frontend.licensing.existingSecret))
}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bdba.fullname" . }}-user-secrets
  labels:
    app: {{ template "bdba.name" . }}
    chart: {{ template "bdba.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if and .Values.frontend.email.smtpPassword (not .Values.frontend.email.existingSecret) }}
  EMAIL_HOST_PASSWORD: {{ .Values.frontend.email.smtpPassword | b64enc | quote }}
  {{- end }}
  {{- if and .Values.frontend.ldap.bindPassword (not .Values.frontend.ldap.existingSecret) }}
  LDAP_BIND_PASSWORD: {{ .Values.frontend.ldap.bindPassword | b64enc | quote }}
  {{- end }}
  {{- if and .Values.frontend.licensing.username .Values.frontend.licensing.password (not .Values.frontend.licensing.existingSecret) }}
  LICENSING_USERNAME: {{ .Values.frontend.licensing.username | b64enc | quote }}
  LICENSING_PASSWORD: {{ .Values.frontend.licensing.password | b64enc | quote }}
  {{- end }}
  {{- if and
    .Values.frontend.licensing.bdportal.tenantId
    .Values.frontend.licensing.bdportal.clientId
    .Values.frontend.licensing.bdportal.clientSecret
    (not .Values.frontend.licensing.existingSecret)
  }}
  BDPORTAL_TENANT_ID: {{ .Values.frontend.licensing.bdportal.tenantId | b64enc | quote }}
  BDPORTAL_CLIENT_ID: {{ .Values.frontend.licensing.bdportal.clientId | b64enc | quote }}
  BDPORTAL_CLIENT_SECRET: {{ .Values.frontend.licensing.bdportal.clientSecret | b64enc | quote }}
  {{- end }}
{{- end }}
