{{- if not .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bdba.fullname" . }}-s3-secrets
  labels:
    app: {{ template "bdba.name" . }}
    chart: {{ template "bdba.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.s3AccessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.s3AccessKeyId | b64enc | quote }}
  {{- end }}
  {{- if .Values.s3SecretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3SecretAccessKey | b64enc | quote }}
  {{- end }}
{{- end }}
