{{- if not .Values.frontend.web.secretKey }}
{{- $secretName := (include "bdba.fullname" . | printf "%s-django-secrets-generated") }}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app: {{ template "bdba.name" . }}
    chart: {{ template "bdba.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
{{- if $existing }}
  DJANGO_SECRET_KEY: {{ index $existing.data "DJANGO_SECRET_KEY" }}
{{- else }}
  DJANGO_SECRET_KEY: {{ include "bdba.generated.djangoSecretKey" . | b64enc | quote }}
{{- end }}
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bdba.fullname" . }}-django-secrets
  labels:
    app: {{ template "bdba.name" . }}
    chart: {{ template "bdba.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.frontend.web.secretKey | b64enc | quote }}
{{- end }}
