apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bdba.fullname" . }}-user-secrets
  labels:
    app: {{ template "bdba.name" . }}
    chart: {{ template "bdba.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.frontend.email.smtpPassword }}
  EMAIL_HOST_PASSWORD: {{ .Values.frontend.email.smtpPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.frontend.ldap.bindPassword }}
  LDAP_BIND_PASSWORD: {{ .Values.frontend.ldap.bindPassword | b64enc | quote }}
  {{- end }}
  {{- if not .Values.frontend.licensing.existingSecret }}
  LICENSING_USERNAME: {{ .Values.frontend.licensing.username | b64enc | quote }}
  LICENSING_PASSWORD: {{ .Values.frontend.licensing.password | b64enc | quote }}
  {{- end }}
