{{- if or (and .Values.frontend.email.smtpPassword (not .Values.frontend.email.existingSecret)) (and .Values.frontend.ldap.bindPassword (not .Values.frontend.ldap.existingSecret)) (not .Values.frontend.licensing.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bdba.fullname" . }}-user-secrets
  labels:
    app: {{ template "bdba.name" . }}
    chart: {{ template "bdba.chart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if and .Values.frontend.email.smtpPassword (not .Values.frontend.email.existingSecret) }}
  EMAIL_HOST_PASSWORD: {{ .Values.frontend.email.smtpPassword | b64enc | quote }}
  {{- end }}
  {{- if and .Values.frontend.ldap.bindPassword (not .Values.frontend.ldap.existingSecret) }}
  LDAP_BIND_PASSWORD: {{ .Values.frontend.ldap.bindPassword | b64enc | quote }}
  {{- end }}
  {{- if not .Values.frontend.licensing.existingSecret }}
  LICENSING_USERNAME: {{ .Values.frontend.licensing.username | b64enc | quote }}
  LICENSING_PASSWORD: {{ .Values.frontend.licensing.password | b64enc | quote }}
  {{- end }}
{{- end }}
